file(GLOB TUI_SOURCES "${SOURCE_DIR}/src/tui/*.c")

foreach(SOURCE_FILE IN LISTS TUI_SOURCES)
    file(READ "${SOURCE_FILE}" SOURCE_TEXT)
    string(REGEX MATCH "ESC=(Back|Partition|Previous)" ESC_PAGE_BACK "${SOURCE_TEXT}")
    if(ESC_PAGE_BACK)
        message(FATAL_ERROR "ESC page navigation remains in ${SOURCE_FILE}")
    endif()
endforeach()

file(READ "${SOURCE_DIR}/src/tui/format_selection.c" FORMAT_SOURCE)
string(FIND "${FORMAT_SOURCE}" "B=Back" FORMAT_BACK_FOOTER)
string(FIND "${FORMAT_SOURCE}" "key == 'b' || key == 'B'" FORMAT_BACK_HANDLER)
string(FIND "${FORMAT_SOURCE}" "key == 27" FORMAT_ESCAPE_HANDLER)
if(FORMAT_BACK_FOOTER EQUAL -1 OR FORMAT_BACK_HANDLER EQUAL -1)
    message(FATAL_ERROR "Format Selection footer/handler does not expose B=Back")
endif()
if(NOT FORMAT_ESCAPE_HANDLER EQUAL -1)
    message(FATAL_ERROR "Format Selection still treats ESC as page navigation")
endif()
