#include <assert.h>
#include <stddef.h>

#include "classicsetup/state.h"

static enum classicsetup_state next(
    enum classicsetup_state state,
    enum classicsetup_event event,
    enum classicsetup_setup_mode mode)
{
    return classicsetup_next_state_for_setup_mode(state, event, mode);
}

static void test_recommended_flow_skips_advanced_screens(void)
{
    assert(next(CLASSICSETUP_STATE_WELCOME, CLASSICSETUP_EVENT_CONTINUE,
                CLASSICSETUP_SETUP_RECOMMENDED) ==
           CLASSICSETUP_STATE_LICENSE_AGREEMENT);
    assert(next(CLASSICSETUP_STATE_LICENSE_AGREEMENT,
                CLASSICSETUP_EVENT_CONTINUE,
                CLASSICSETUP_SETUP_RECOMMENDED) ==
           CLASSICSETUP_STATE_SETUP_MODE);
    assert(next(CLASSICSETUP_STATE_SETUP_MODE, CLASSICSETUP_EVENT_CONTINUE,
                CLASSICSETUP_SETUP_RECOMMENDED) ==
           CLASSICSETUP_STATE_GUI_TRANSITION);
    assert(next(CLASSICSETUP_STATE_GUI_TRANSITION,
                CLASSICSETUP_EVENT_CONTINUE,
                CLASSICSETUP_SETUP_RECOMMENDED) ==
           CLASSICSETUP_STATE_NEXT_STAGE);
    assert(next(CLASSICSETUP_STATE_GUI_TRANSITION,
                CLASSICSETUP_EVENT_BACK,
                CLASSICSETUP_SETUP_RECOMMENDED) ==
           CLASSICSETUP_STATE_SETUP_MODE);
    assert(next(CLASSICSETUP_STATE_RECOMMENDED_DISK,
                CLASSICSETUP_EVENT_CONTINUE,
                CLASSICSETUP_SETUP_RECOMMENDED) ==
           CLASSICSETUP_STATE_NETWORK);
    assert(next(CLASSICSETUP_STATE_NETWORK,
                CLASSICSETUP_EVENT_CONTINUE,
                CLASSICSETUP_SETUP_RECOMMENDED) ==
           CLASSICSETUP_STATE_WINDOWS_VERSION);
    assert(next(CLASSICSETUP_STATE_WINDOWS_VERSION,
                CLASSICSETUP_EVENT_CONTINUE,
                CLASSICSETUP_SETUP_RECOMMENDED) ==
           CLASSICSETUP_STATE_WINDOWS_DOWNLOAD);
    assert(next(CLASSICSETUP_STATE_WINDOWS_DOWNLOAD,
                CLASSICSETUP_EVENT_CONTINUE,
                CLASSICSETUP_SETUP_RECOMMENDED) ==
           CLASSICSETUP_STATE_INSTALL_OPTIONS);
    assert(next(CLASSICSETUP_STATE_INSTALL_OPTIONS,
                CLASSICSETUP_EVENT_CONTINUE,
                CLASSICSETUP_SETUP_RECOMMENDED) ==
           CLASSICSETUP_STATE_INSTALL_SUMMARY);
    assert(next(CLASSICSETUP_STATE_INSTALL_SUMMARY,
                CLASSICSETUP_EVENT_CONTINUE,
                CLASSICSETUP_SETUP_RECOMMENDED) ==
           CLASSICSETUP_STATE_RECOMMENDED_RESULT);
    assert(next(CLASSICSETUP_STATE_RECOMMENDED_RESULT,
                CLASSICSETUP_EVENT_CONTINUE,
                CLASSICSETUP_SETUP_RECOMMENDED) ==
           CLASSICSETUP_STATE_NEXT_STAGE);
    assert(next(CLASSICSETUP_STATE_NEXT_STAGE,
                CLASSICSETUP_EVENT_CONTINUE,
                CLASSICSETUP_SETUP_RECOMMENDED) ==
           CLASSICSETUP_STATE_EXIT);
}

static void test_advanced_flow_is_preserved(void)
{
    enum classicsetup_state states[] = {
        CLASSICSETUP_STATE_WELCOME,
        CLASSICSETUP_STATE_LICENSE_AGREEMENT,
        CLASSICSETUP_STATE_SETUP_MODE,
        CLASSICSETUP_STATE_KEYBOARD,
        CLASSICSETUP_STATE_INSTALL_MODE,
        CLASSICSETUP_STATE_DISK,
        CLASSICSETUP_STATE_PARTITION,
        CLASSICSETUP_STATE_FORMAT,
        CLASSICSETUP_STATE_APPLY_PREVIEW,
        CLASSICSETUP_STATE_APPLY_CONFIRMATION,
        CLASSICSETUP_STATE_APPLY_RESULT,
        CLASSICSETUP_STATE_FORMAT_APPLY_PREVIEW,
        CLASSICSETUP_STATE_FORMAT_APPLY_CONFIRMATION,
        CLASSICSETUP_STATE_FORMAT_APPLY_RESULT,
        CLASSICSETUP_STATE_GUI_TRANSITION,
        CLASSICSETUP_STATE_NEXT_STAGE,
        CLASSICSETUP_STATE_EXIT
    };
    size_t index;

    for (index = 0; index + 1 < sizeof(states) / sizeof(states[0]); ++index) {
        assert(next(states[index], CLASSICSETUP_EVENT_CONTINUE,
                    CLASSICSETUP_SETUP_ADVANCED) == states[index + 1]);
    }
}

static void test_back_and_cancel_policy(void)
{
    assert(next(CLASSICSETUP_STATE_LICENSE_AGREEMENT,
                CLASSICSETUP_EVENT_BACK,
                CLASSICSETUP_SETUP_RECOMMENDED) ==
           CLASSICSETUP_STATE_WELCOME);
    assert(next(CLASSICSETUP_STATE_KEYBOARD, CLASSICSETUP_EVENT_BACK,
                CLASSICSETUP_SETUP_RECOMMENDED) ==
           CLASSICSETUP_STATE_SETUP_MODE);
    assert(next(CLASSICSETUP_STATE_RECOMMENDED_DISK,
                CLASSICSETUP_EVENT_BACK,
                CLASSICSETUP_SETUP_RECOMMENDED) ==
           CLASSICSETUP_STATE_SETUP_MODE);
    assert(next(CLASSICSETUP_STATE_NETWORK, CLASSICSETUP_EVENT_BACK,
                CLASSICSETUP_SETUP_RECOMMENDED) ==
           CLASSICSETUP_STATE_RECOMMENDED_DISK);
    assert(next(CLASSICSETUP_STATE_INSTALL_SUMMARY, CLASSICSETUP_EVENT_BACK,
                CLASSICSETUP_SETUP_RECOMMENDED) ==
           CLASSICSETUP_STATE_INSTALL_OPTIONS);
    assert(next(CLASSICSETUP_STATE_INSTALL_MODE, CLASSICSETUP_EVENT_BACK,
                CLASSICSETUP_SETUP_ADVANCED) ==
           CLASSICSETUP_STATE_KEYBOARD);
    assert(next(CLASSICSETUP_STATE_DISK, CLASSICSETUP_EVENT_BACK,
                CLASSICSETUP_SETUP_ADVANCED) ==
           CLASSICSETUP_STATE_INSTALL_MODE);
    assert(next(CLASSICSETUP_STATE_FORMAT, CLASSICSETUP_EVENT_CANCEL,
                CLASSICSETUP_SETUP_ADVANCED) ==
           CLASSICSETUP_STATE_PARTITION);
    assert(next(CLASSICSETUP_STATE_FORMAT_APPLY_CONFIRMATION,
                CLASSICSETUP_EVENT_CANCEL,
                CLASSICSETUP_SETUP_ADVANCED) ==
           CLASSICSETUP_STATE_FORMAT_APPLY_CONFIRMATION);
    assert(next(CLASSICSETUP_STATE_GUI_TRANSITION,
                CLASSICSETUP_EVENT_BACK,
                CLASSICSETUP_SETUP_RECOMMENDED) ==
           CLASSICSETUP_STATE_SETUP_MODE);
    assert(next(CLASSICSETUP_STATE_GUI_TRANSITION,
                CLASSICSETUP_EVENT_BACK,
                CLASSICSETUP_SETUP_ADVANCED) ==
           CLASSICSETUP_STATE_FORMAT_APPLY_RESULT);
}

static void test_quit_request_policy(void)
{
    enum classicsetup_state states[] = {
        CLASSICSETUP_STATE_WELCOME,
        CLASSICSETUP_STATE_LICENSE_AGREEMENT,
        CLASSICSETUP_STATE_SETUP_MODE,
        CLASSICSETUP_STATE_GUI_TRANSITION,
        CLASSICSETUP_STATE_KEYBOARD,
        CLASSICSETUP_STATE_RECOMMENDED_DISK,
        CLASSICSETUP_STATE_NETWORK,
        CLASSICSETUP_STATE_WINDOWS_VERSION,
        CLASSICSETUP_STATE_WINDOWS_DOWNLOAD,
        CLASSICSETUP_STATE_INSTALL_OPTIONS,
        CLASSICSETUP_STATE_INSTALL_SUMMARY,
        CLASSICSETUP_STATE_RECOMMENDED_RESULT,
        CLASSICSETUP_STATE_INSTALL_MODE,
        CLASSICSETUP_STATE_DISK,
        CLASSICSETUP_STATE_PARTITION,
        CLASSICSETUP_STATE_FORMAT,
        CLASSICSETUP_STATE_APPLY_PREVIEW,
        CLASSICSETUP_STATE_APPLY_CONFIRMATION,
        CLASSICSETUP_STATE_APPLY_RESULT,
        CLASSICSETUP_STATE_FORMAT_APPLY_PREVIEW,
        CLASSICSETUP_STATE_FORMAT_APPLY_CONFIRMATION,
        CLASSICSETUP_STATE_FORMAT_APPLY_RESULT,
        CLASSICSETUP_STATE_AFTER_FORMAT,
        CLASSICSETUP_STATE_NEXT_STAGE
    };
    size_t index;

    for (index = 0; index < sizeof(states) / sizeof(states[0]); ++index) {
        assert(next(states[index], CLASSICSETUP_EVENT_QUIT_REQUEST,
                    CLASSICSETUP_SETUP_RECOMMENDED) == states[index]);
        assert(classicsetup_resolve_quit_request(states[index], false) ==
               states[index]);
        assert(classicsetup_resolve_quit_request(states[index], true) ==
               CLASSICSETUP_STATE_EXIT);
    }
}

int main(void)
{
    test_recommended_flow_skips_advanced_screens();
    test_advanced_flow_is_preserved();
    test_back_and_cancel_policy();
    test_quit_request_policy();
    assert(classicsetup_next_state(
               (enum classicsetup_state)999,
               CLASSICSETUP_EVENT_CONTINUE) == CLASSICSETUP_STATE_EXIT);
    return 0;
}
