# CMake generated Testfile for 
# Source directory: /home/yskyh06/linux-workspace/classicsetup
# Build directory: /home/yskyh06/linux-workspace/classicsetup/build-m13-sanitize
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(state_transitions "/home/yskyh06/linux-workspace/classicsetup/build-m13-sanitize/classicsetup_state_test")
set_tests_properties(state_transitions PROPERTIES  _BACKTRACE_TRIPLES "/home/yskyh06/linux-workspace/classicsetup/CMakeLists.txt;224;add_test;/home/yskyh06/linux-workspace/classicsetup/CMakeLists.txt;0;")
add_test(gui_navigation "/home/yskyh06/linux-workspace/classicsetup/build-m13-sanitize/classicsetup_gui_test")
set_tests_properties(gui_navigation PROPERTIES  _BACKTRACE_TRIPLES "/home/yskyh06/linux-workspace/classicsetup/CMakeLists.txt;253;add_test;/home/yskyh06/linux-workspace/classicsetup/CMakeLists.txt;0;")
add_test(windows_source_pipeline "/home/yskyh06/linux-workspace/classicsetup/build-m13-sanitize/classicsetup_source_test")
set_tests_properties(windows_source_pipeline PROPERTIES  _BACKTRACE_TRIPLES "/home/yskyh06/linux-workspace/classicsetup/CMakeLists.txt;290;add_test;/home/yskyh06/linux-workspace/classicsetup/CMakeLists.txt;0;")
add_test(uup_backend_model "/home/yskyh06/linux-workspace/classicsetup/build-m13-sanitize/classicsetup_uup_test")
set_tests_properties(uup_backend_model PROPERTIES  _BACKTRACE_TRIPLES "/home/yskyh06/linux-workspace/classicsetup/CMakeLists.txt;318;add_test;/home/yskyh06/linux-workspace/classicsetup/CMakeLists.txt;0;")
add_test(network_model "/home/yskyh06/linux-workspace/classicsetup/build-m13-sanitize/classicsetup_network_test")
set_tests_properties(network_model PROPERTIES  _BACKTRACE_TRIPLES "/home/yskyh06/linux-workspace/classicsetup/CMakeLists.txt;337;add_test;/home/yskyh06/linux-workspace/classicsetup/CMakeLists.txt;0;")
add_test(disk_scan "/home/yskyh06/linux-workspace/classicsetup/build-m13-sanitize/classicsetup_disk_test")
set_tests_properties(disk_scan PROPERTIES  _BACKTRACE_TRIPLES "/home/yskyh06/linux-workspace/classicsetup/CMakeLists.txt;359;add_test;/home/yskyh06/linux-workspace/classicsetup/CMakeLists.txt;0;")
add_test(partition_scan "/home/yskyh06/linux-workspace/classicsetup/build-m13-sanitize/classicsetup_partition_test")
set_tests_properties(partition_scan PROPERTIES  _BACKTRACE_TRIPLES "/home/yskyh06/linux-workspace/classicsetup/CMakeLists.txt;383;add_test;/home/yskyh06/linux-workspace/classicsetup/CMakeLists.txt;0;")
add_test(partition_plan "/home/yskyh06/linux-workspace/classicsetup/build-m13-sanitize/classicsetup_partition_plan_test")
set_tests_properties(partition_plan PROPERTIES  _BACKTRACE_TRIPLES "/home/yskyh06/linux-workspace/classicsetup/CMakeLists.txt;407;add_test;/home/yskyh06/linux-workspace/classicsetup/CMakeLists.txt;0;")
add_test(format_plan "/home/yskyh06/linux-workspace/classicsetup/build-m13-sanitize/classicsetup_format_test")
set_tests_properties(format_plan PROPERTIES  _BACKTRACE_TRIPLES "/home/yskyh06/linux-workspace/classicsetup/CMakeLists.txt;430;add_test;/home/yskyh06/linux-workspace/classicsetup/CMakeLists.txt;0;")
add_test(apply_safety_and_render "/home/yskyh06/linux-workspace/classicsetup/build-m13-sanitize/classicsetup_apply_test")
set_tests_properties(apply_safety_and_render PROPERTIES  _BACKTRACE_TRIPLES "/home/yskyh06/linux-workspace/classicsetup/CMakeLists.txt;460;add_test;/home/yskyh06/linux-workspace/classicsetup/CMakeLists.txt;0;")
add_test(format_apply "/home/yskyh06/linux-workspace/classicsetup/build-m13-sanitize/classicsetup_format_apply_test")
set_tests_properties(format_apply PROPERTIES  _BACKTRACE_TRIPLES "/home/yskyh06/linux-workspace/classicsetup/CMakeLists.txt;488;add_test;/home/yskyh06/linux-workspace/classicsetup/CMakeLists.txt;0;")
add_test(recommended_policy "/home/yskyh06/linux-workspace/classicsetup/build-m13-sanitize/classicsetup_recommended_test")
set_tests_properties(recommended_policy PROPERTIES  _BACKTRACE_TRIPLES "/home/yskyh06/linux-workspace/classicsetup/CMakeLists.txt;526;add_test;/home/yskyh06/linux-workspace/classicsetup/CMakeLists.txt;0;")
add_test(tui_compact_layout "/home/yskyh06/linux-workspace/classicsetup/build-m13-sanitize/classicsetup_tui_layout_test")
set_tests_properties(tui_compact_layout PROPERTIES  _BACKTRACE_TRIPLES "/home/yskyh06/linux-workspace/classicsetup/CMakeLists.txt;554;add_test;/home/yskyh06/linux-workspace/classicsetup/CMakeLists.txt;0;")
add_test(key_mapping "/home/yskyh06/linux-workspace/classicsetup/build-m13-sanitize/classicsetup_key_mapping_test")
set_tests_properties(key_mapping PROPERTIES  _BACKTRACE_TRIPLES "/home/yskyh06/linux-workspace/classicsetup/CMakeLists.txt;582;add_test;/home/yskyh06/linux-workspace/classicsetup/CMakeLists.txt;0;")
add_test(tui_no_function_keys "/usr/bin/cmake" "-DSOURCE_DIR=/home/yskyh06/linux-workspace/classicsetup" "-P" "/home/yskyh06/linux-workspace/classicsetup/tests/check_no_function_keys.cmake")
set_tests_properties(tui_no_function_keys PROPERTIES  _BACKTRACE_TRIPLES "/home/yskyh06/linux-workspace/classicsetup/CMakeLists.txt;583;add_test;/home/yskyh06/linux-workspace/classicsetup/CMakeLists.txt;0;")
add_test(tui_back_key_policy "/usr/bin/cmake" "-DSOURCE_DIR=/home/yskyh06/linux-workspace/classicsetup" "-P" "/home/yskyh06/linux-workspace/classicsetup/tests/check_back_key_policy.cmake")
set_tests_properties(tui_back_key_policy PROPERTIES  _BACKTRACE_TRIPLES "/home/yskyh06/linux-workspace/classicsetup/CMakeLists.txt;589;add_test;/home/yskyh06/linux-workspace/classicsetup/CMakeLists.txt;0;")
add_test(fido_runtime_staging "/home/yskyh06/linux-workspace/classicsetup/tests/fido_staging_test.sh" "/home/yskyh06/linux-workspace/classicsetup")
set_tests_properties(fido_runtime_staging PROPERTIES  _BACKTRACE_TRIPLES "/home/yskyh06/linux-workspace/classicsetup/CMakeLists.txt;595;add_test;/home/yskyh06/linux-workspace/classicsetup/CMakeLists.txt;0;")
